version: '3.8'

services:
  web:
    build: .
    container_name: django_portfolio
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DEBUG: "False"
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgres://samandar:1234@db:5432/portfolio

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: samandar
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
