# Generated by Django 5.1.3 on 2024-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
