# Generated by Django 5.1.3 on 2024-11-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_user_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='i_class_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
