# Generated by Django 5.1.3 on 2024-11-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='i_class_name',
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_image/'),
        ),
    ]
