# Generated by Django 5.1.3 on 2024-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_service_i_class_name_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
