# Generated by Django 5.1.3 on 2024-11-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_volunteers',
            new_name='completed_tasks',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='total_projects',
            new_name='open_source_projects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_donations',
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
