# Generated by Django 5.1.3 on 2024-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_total_volunteers_user_completed_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
